//-------------------------------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by EntitiesToDTOs.v3.1 (entitiestodtos.codeplex.com).
//     Timestamp: 2013/07/09 - 01:42:02
//
//     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
//-------------------------------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Runtime.Serialization;
using System.Text;
using VS2012TestEdmx.Banking;
using VS2012TestEdmx.Enums;
using SandboxVS2010.Enums;

namespace VS2012TestEdmx.DTOs
{
    [DataContract()]
    public partial class ClientDTO
    {
        [DataMember()]
        public Int32 ClientID { get; set; }

        [DataMember()]
        public String FirstName { get; set; }

        [DataMember()]
        public String LastName { get; set; }

        [DataMember()]
        public ClientType TypeOfClient { get; set; }

        [DataMember()]
        public List<Int32> Accounts_AccountID { get; set; }

        public ClientDTO()
        {
        }

        public ClientDTO(Int32 clientID, String firstName, String lastName, ClientType typeOfClient, List<Int32> accounts_AccountID)
        {
			this.ClientID = clientID;
			this.FirstName = firstName;
			this.LastName = lastName;
			this.TypeOfClient = typeOfClient;
			this.Accounts_AccountID = accounts_AccountID;
        }
    }

    [DataContract()]
    public partial class AccountDTO
    {
        [DataMember()]
        public Int32 AccountID { get; set; }

        [DataMember()]
        public Decimal Balance { get; set; }

        [DataMember()]
        public CurrencyType Currency { get; set; }

        [DataMember()]
        public AccountType TypeOfAccount { get; set; }

        [DataMember()]
        public Int32 Client_ClientID { get; set; }

        public AccountDTO()
        {
        }

        public AccountDTO(Int32 accountID, Decimal balance, CurrencyType currency, AccountType typeOfAccount, Int32 client_ClientID)
        {
			this.AccountID = accountID;
			this.Balance = balance;
			this.Currency = currency;
			this.TypeOfAccount = typeOfAccount;
			this.Client_ClientID = client_ClientID;
        }
    }
}
