//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Data.Objects;
using System.Data.EntityClient;

namespace CarWorkshopPOCO
{
    public partial class CarWorkshopContainer : ObjectContext
    {
        public const string ConnectionString = "name=CarWorkshopContainer";
        public const string ContainerName = "CarWorkshopContainer";
    
        #region Constructors
    
        public CarWorkshopContainer()
            : base(ConnectionString, ContainerName)
        {
            this.ContextOptions.LazyLoadingEnabled = true;
        }
    
        public CarWorkshopContainer(string connectionString)
            : base(connectionString, ContainerName)
        {
            this.ContextOptions.LazyLoadingEnabled = true;
        }
    
        public CarWorkshopContainer(EntityConnection connection)
            : base(connection, ContainerName)
        {
            this.ContextOptions.LazyLoadingEnabled = true;
        }
    
        #endregion
    
        #region ObjectSet Properties
    
        public ObjectSet<Employee> Employees
        {
            get { return _employees  ?? (_employees = CreateObjectSet<Employee>("Employees")); }
        }
        private ObjectSet<Employee> _employees;
    
        public ObjectSet<EmployeeType> EmployeeTypes
        {
            get { return _employeeTypes  ?? (_employeeTypes = CreateObjectSet<EmployeeType>("EmployeeTypes")); }
        }
        private ObjectSet<EmployeeType> _employeeTypes;
    
        public ObjectSet<Vehicle> Vehicles
        {
            get { return _vehicles  ?? (_vehicles = CreateObjectSet<Vehicle>("Vehicles")); }
        }
        private ObjectSet<Vehicle> _vehicles;

        #endregion

    }
}
