//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Data.Entity;
using System.Data.Entity.Infrastructure;
using System.Data.Objects;

namespace CarWorkshopDbContextWCF
{
    public partial class CarWorkshopContainer : DbContext
    {
        public CarWorkshopContainer()
            : this(false) { }
    
        public CarWorkshopContainer(bool proxyCreationEnabled)	    
            : base("name=CarWorkshopContainer")
        {
            this.Configuration.ProxyCreationEnabled = proxyCreationEnabled;
        }
    
        public CarWorkshopContainer(string connectionString)
          : this(connectionString, false) { }
    
        public CarWorkshopContainer(string connectionString, bool proxyCreationEnabled)
            : base(connectionString)
        {
            this.Configuration.ProxyCreationEnabled = proxyCreationEnabled;
        }	
    
        public ObjectContext ObjectContext
        {
          get { return ((IObjectContextAdapter)this).ObjectContext; }
        }
    
    	protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    	
        public DbSet<Employee> Employees { get; set; }
        public DbSet<EmployeeType> EmployeeTypes { get; set; }
        public DbSet<Vehicle> Vehicles { get; set; }
    }
}
