//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Runtime.Serialization;


namespace CarWorkshopDbContextWCF
{
    [DataContract(IsReference = true)]
    [KnownType(typeof(EmployeeType))]
    public partial class Employee
    {
        [DataMember]
        public int EmployeeID { get; set; }
        [DataMember]
        public string FirstName { get; set; }
        [DataMember]
        public string LastName { get; set; }
        [DataMember]
        public double Salary { get; set; }
        [DataMember]
        public Nullable<System.DateTime> Birthdate { get; set; }
        [DataMember]
        public string Event { get; set; }
    
        [DataMember]
        public virtual EmployeeType EmployeeType { get; set; }
    }
    
}
