//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Runtime.Serialization;


namespace CarWorkshopDbContextWCF
{
    [DataContract(IsReference = true)]
    [KnownType(typeof(EmployeeMechanic))]
    [KnownType(typeof(EmployeePainter))]
    [KnownType(typeof(Employee))]
    public abstract partial class EmployeeType
    {
        public EmployeeType()
        {
            this.Employees = new HashSet<Employee>();
        }
    
        [DataMember]
        public int EmployeeTypeID { get; set; }
    
        [DataMember]
        public virtual ICollection<Employee> Employees { get; set; }
    }
    
}
