//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Runtime.Serialization;


namespace CarWorkshopDbContextWCF
{
    [DataContract(IsReference = true)]
    [KnownType(typeof(VehicleBikeNormal))]
    [KnownType(typeof(VehicleBikeSidecar))]
    public partial class VehicleBike : Vehicle
    {
        public VehicleBike()
        {
            this.ComplexProperty = new MyComplexT();
        }
    
        [DataMember]
        public int Passengers { get; set; }
    
        [DataMember]
        public MyComplexT ComplexProperty { get; set; }
    }
    
}
