//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VS2012TestEdmx
{
    using System;
    
    public partial class Location
    {
        public long Country { get; set; }
        public int State { get; set; }
        public string Address { get; set; }
        public string ZipCode { get; set; }
    }
}
