//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VS2012TestEdmx
{
    using System;
    using System.Collections.Generic;
    
    public partial class ZooPark
    {
        public ZooPark()
        {
            this.Location = new Location();
        }
    
        public int ZooParkID { get; set; }
    
        public Location Location { get; set; }
    }
}
