//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace CarWorkshopDbContext
{
    public partial class VehicleBike : Vehicle
    {
        public VehicleBike()
        {
            this.ComplexProperty = new MyComplexT();
        }
    
        public int Passengers { get; set; }
    
        public MyComplexT ComplexProperty { get; set; }
    }
    
}
