//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;

namespace CarWorkshopPOCO
{
    public partial class Vehicle
    {
        #region Primitive Properties
    
        public virtual int VehicleID
        {
            get;
            set;
        }

        #endregion

        #region Navigation Properties
    
        public virtual Employee Employee
        {
            get { return _employee; }
            set
            {
                if (!ReferenceEquals(_employee, value))
                {
                    var previousValue = _employee;
                    _employee = value;
                    FixupEmployee(previousValue);
                }
            }
        }
        private Employee _employee;

        #endregion

        #region Association Fixup
    
        private void FixupEmployee(Employee previousValue)
        {
            if (previousValue != null && previousValue.Vehicles.Contains(this))
            {
                previousValue.Vehicles.Remove(this);
            }
    
            if (Employee != null)
            {
                if (!Employee.Vehicles.Contains(this))
                {
                    Employee.Vehicles.Add(this);
                }
            }
        }

        #endregion

    }
}
