//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;

namespace CarWorkshopPOCO
{
    public partial class VehicleBike : Vehicle
    {
        #region Primitive Properties
    
        public virtual int Passengers
        {
            get;
            set;
        }

        #endregion

        #region Complex Properties
    
        public virtual MyComplexT ComplexProperty
        {
            get { return _complexProperty; }
            set { _complexProperty = value; }
        }
        private MyComplexT _complexProperty = new MyComplexT();

        #endregion

    }
}
