//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VS2012TestEdmx.Banking
{
    using System;
    using System.Collections.Generic;
    
    public partial class Account
    {
        public int AccountID { get; set; }
        public decimal Balance { get; set; }
        public CurrencyType Currency { get; set; }
        public SandboxVS2010.Enums.AccountType TypeOfAccount { get; set; }
    
        public virtual Client Client { get; set; }
    }
}
