//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VS2012TestEdmx.Banking
{
    using System;
    
    public enum CurrencyType : short
    {
        USD = 0,
        UYU = 1,
        ARS = 2,
        BRL = 3
    }
}
